"""G2 — Requirements Traceability Matrix (deterministic projection).

The RTM is NOT generated by an LLM: it is a faithful projection of the approved
requirement repository. Every approved requirement yields exactly one row linking its
formal SRS id ↔ internal id ↔ SRS section ↔ source evidence — so the SRS can never
contain a line that does not trace back to a source, and vice-versa (P7 TC7.2).
"""

from __future__ import annotations

import csv
import io

from ..models import Requirement
from .common import approved_sorted, md_cell, source_label, source_quotes
from .srs_template import assign_srs_ids, section_for

RTM_COLUMNS = ["SRS ID", "Internal ID", "Requirement", "Type", "Priority", "SRS Section", "Source(s)", "Evidence"]

# The delivered RTM is a CSV whose rows are the SRS items (requirements + Design/UI elements +
# glossary terms). The trailing phase/status columns are intentionally BLANK — a template the team
# fills as the SRS is traced through Design → Implementation → Testing, plus a per-item Status.
RTM_CSV_COLUMNS = ["ID", "Category", "SRS Section", "Requirement",
                   "Design", "Implementation", "Testing", "Status"]
_RTM_BLANK = ["", "", "", ""]   # Design, Implementation, Testing, Status — for future use

_CATEGORY_LABEL = {
    "functional": "Functional", "non_functional": "Non-Functional", "business": "Business Rule",
    "constraint": "Constraint", "assumption": "Assumption",
}


def build_rtm_matrix(
    requirements: list[Requirement], id_map: dict[str, str] | None = None, *,
    design_elements: list[dict] | None = None, glossary_terms: list[tuple[str, str]] | None = None,
) -> list[dict]:
    """Rows for the delivered RTM CSV: every requirement in the SRS, then the Design/UI elements
    (§3.1 tokens), then the glossary terms (Appendix A). Each row carries its id, category, SRS
    section and the item text (the `Requirement` column); phase/status columns are added blank when
    the CSV is rendered. Reuses `build_rtm` for the requirement ordering + id/section, so the RTM and
    SRS always agree."""
    rows: list[dict] = []
    con = asm = 0
    for r in build_rtm(requirements, id_map):                       # requirements (REQ/NFR/BR/…)
        sid = r["srs_id"]
        if sid == "—":                                              # constraints/assumptions carry no tag
            if r["rtype"] == "constraint":
                con += 1
                sid = f"CON-{con}"
            elif r["rtype"] == "assumption":
                asm += 1
                sid = f"ASM-{asm}"
            else:
                sid = r["internal_id"]
        rows.append({
            "id": sid,
            "category": _CATEGORY_LABEL.get(r["rtype"], r["rtype"].replace("_", " ").title()),
            "section": r["section"],
            "requirement": r["statement"],
        })
    for e in (design_elements or []):                               # Design & UI elements (§3.1)
        rows.append({"id": e["id"], "category": "Design & UI", "section": e["section"], "requirement": e["text"]})
    for i, (term, defn) in enumerate(glossary_terms or [], 1):      # glossary terms (Appendix A)
        rows.append({"id": f"TERM-{i}", "category": "Glossary", "section": "Appendix A",
                     "requirement": f"{term} — {defn}"})
    return rows


def rtm_csv(rows: list[dict]) -> str:
    """Render the RTM rows as CSV (RFC-4180 quoting via the csv module — safe for commas/quotes)."""
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(RTM_CSV_COLUMNS)
    for row in rows:
        w.writerow([row["id"], row["category"], row["section"], row["requirement"], *_RTM_BLANK])
    return buf.getvalue()


def build_rtm(requirements: list[Requirement], id_map: dict[str, str] | None = None) -> list[dict]:
    """One row per approved requirement. `id_map` (internal -> formal) is reused from the
    SRS so both artifacts agree on REQ-n/NFR-n/BR-n; recomputed if not supplied."""
    approved = approved_sorted(requirements)
    id_map = id_map if id_map is not None else assign_srs_ids(approved)
    rows: list[dict] = []
    for r in approved:
        rows.append(
            {
                "srs_id": id_map.get(r.id, "—"),  # constraints/assumptions have no tagged id
                "internal_id": r.id,
                "statement": r.statement,
                "rtype": r.rtype.value,
                "priority": r.priority.value if r.priority else "—",
                "section": section_for(r),
                "sources": source_label(r),
                "evidence": source_quotes(r),
            }
        )
    # Order: tagged ids first (REQ, NFR, BR) in numeric order, then untagged (§2.5/§2.7).
    def sort_key(row: dict) -> tuple:
        sid = row["srs_id"]
        if sid == "—":
            return (3, 0, row["internal_id"])
        prefix, num = sid.split("-")
        rank = {"REQ": 0, "NFR": 1, "BR": 2}.get(prefix, 3)
        return (rank, int(num), row["internal_id"])

    rows.sort(key=sort_key)
    return rows


def rtm_markdown(rows: list[dict]) -> str:
    """Render the RTM as a Markdown table."""
    out = ["| " + " | ".join(RTM_COLUMNS) + " |", "|" + "|".join(["---"] * len(RTM_COLUMNS)) + "|"]
    for row in rows:
        cells = [
            row["srs_id"],
            row["internal_id"],
            md_cell(row["statement"]),
            row["rtype"],
            row.get("priority", "—"),
            md_cell(row["section"]),
            md_cell(row["sources"]),
            md_cell(row["evidence"]),
        ]
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out) + "\n"


def traceability_check(requirements: list[Requirement]) -> dict:
    """Assert the projection is complete: every approved requirement has a row, an SRS
    section, and at least one source. Returns a small report (used by TC7.2 + the run report)."""
    approved = approved_sorted(requirements)
    rows = build_rtm(approved)
    by_internal = {row["internal_id"] for row in rows}
    missing_rows = [r.id for r in approved if r.id not in by_internal]
    no_source = [r.id for r in approved if not r.source_refs]
    no_section = [row["internal_id"] for row in rows if not row["section"]]
    return {
        "approved": len(approved),
        "rows": len(rows),
        "missing_rows": missing_rows,
        "requirements_without_source": no_source,
        "rows_without_section": no_section,
        "complete": not (missing_rows or no_source or no_section),
    }
